#!/usr/bin/env python3
"""Convert the Vite build output into a self-contained Arduino header."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DIST_INDEX = ROOT / "webui" / "dist" / "index.html"
DIST_ROOT = DIST_INDEX.parent
OUT = ROOT / "src" / "WebUIAssets.h"


def raw_literal(value: str) -> str:
    marker = "WEBUIHTML"
    while f"){marker}\"" in value:
        marker += "_"
    return f'R"{marker}({value}){marker}"'


def inline_assets(html: str) -> str:
    def inline_style(match: re.Match[str]) -> str:
        href = match.group(1)
        css_path = (DIST_ROOT / href.lstrip("/")).resolve()
        if not css_path.is_file() or DIST_ROOT.resolve() not in css_path.parents:
            raise FileNotFoundError(href)
        return f"<style>{css_path.read_text(encoding='utf-8')}</style>"

    def inline_script(match: re.Match[str]) -> str:
        src = match.group(1)
        js_path = (DIST_ROOT / src.lstrip("/")).resolve()
        if not js_path.is_file() or DIST_ROOT.resolve() not in js_path.parents:
            raise FileNotFoundError(src)
        return f"<script>{js_path.read_text(encoding='utf-8')}</script>"

    html = re.sub(r'<link rel="stylesheet" crossorigin href="([^"]+)">', inline_style, html)
    html = re.sub(r'<script type="module" crossorigin src="([^"]+)"></script>', inline_script, html)
    return html


def main() -> int:
    if not DIST_INDEX.exists():
        print("webui/dist/index.html not found. Run `npm run build` in webui first.")
        return 1

    html = inline_assets(DIST_INDEX.read_text(encoding="utf-8"))
    header = """#pragma once

// Generated by scripts/build_webui.py. Do not edit by hand.
static const char WEBUI_INDEX_HTML[] PROGMEM = %s;
""" % raw_literal(html)
    OUT.write_text(header, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(html)} bytes of HTML)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
